        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:14 2019
        MODULE BISECT__genmod
          INTERFACE 
            SUBROUTINE BISECT(D,E,ACHEPS,IFAIL)
              REAL(KIND=8), INTENT(INOUT) :: D(0:)
              REAL(KIND=8), INTENT(INOUT) :: E(0:)
              REAL(KIND=8), INTENT(IN) :: ACHEPS
              INTEGER(KIND=4), INTENT(INOUT) :: IFAIL
            END SUBROUTINE BISECT
          END INTERFACE 
        END MODULE BISECT__genmod
