        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:16 2019
        MODULE CHECON__genmod
          INTERFACE 
            SUBROUTINE CHECON(LOADS,OLDLDS,TOL,CONVERGED)
              REAL(KIND=8), INTENT(IN) :: LOADS(0:)
              REAL(KIND=8), INTENT(INOUT) :: OLDLDS(0:)
              REAL(KIND=8), INTENT(IN) :: TOL
              LOGICAL(KIND=4), INTENT(OUT) :: CONVERGED
            END SUBROUTINE CHECON
          END INTERFACE 
        END MODULE CHECON__genmod
