        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 12:05:24 2019
        MODULE CHOBK1__genmod
          INTERFACE 
            SUBROUTINE CHOBK1(KB,LOADS)
              REAL(KIND=8), INTENT(IN) :: KB(:,:)
              REAL(KIND=8), INTENT(INOUT) :: LOADS(0:)
            END SUBROUTINE CHOBK1
          END INTERFACE 
        END MODULE CHOBK1__genmod
