        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:16 2019
        MODULE COMRED__genmod
          INTERFACE 
            SUBROUTINE COMRED(BK,N)
              COMPLEX(KIND=8), INTENT(INOUT) :: BK(:)
              INTEGER(KIND=4), INTENT(IN) :: N
            END SUBROUTINE COMRED
          END INTERFACE 
        END MODULE COMRED__genmod
