        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:18 2019
        MODULE FMACAT__genmod
          INTERFACE 
            SUBROUTINE FMACAT(VMFL,ACAT)
              REAL(KIND=8), INTENT(IN) :: VMFL(:)
              REAL(KIND=8), INTENT(OUT) :: ACAT(:,:)
            END SUBROUTINE FMACAT
          END INTERFACE 
        END MODULE FMACAT__genmod
