        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:18 2019
        MODULE FORMNF__genmod
          INTERFACE 
            SUBROUTINE FORMNF(NF)
              INTEGER(KIND=4), INTENT(INOUT) :: NF(:,:)
            END SUBROUTINE FORMNF
          END INTERFACE 
        END MODULE FORMNF__genmod
