        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:13 2019
        MODULE GLOB_TO_AXIAL__genmod
          INTERFACE 
            SUBROUTINE GLOB_TO_AXIAL(AXIAL,GLOBAL,COORD)
              REAL(KIND=8), INTENT(OUT) :: AXIAL
              REAL(KIND=8), INTENT(IN) :: GLOBAL(:)
              REAL(KIND=8), INTENT(IN) :: COORD(:,:)
            END SUBROUTINE GLOB_TO_AXIAL
          END INTERFACE 
        END MODULE GLOB_TO_AXIAL__genmod
