        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:16 2019
        MODULE INVAR__genmod
          INTERFACE 
            SUBROUTINE INVAR(STRESS,SIGM,DSBAR,THETA)
              REAL(KIND=8), INTENT(IN) :: STRESS(:)
              REAL(KIND=8) ,OPTIONAL, INTENT(OUT) :: SIGM
              REAL(KIND=8) ,OPTIONAL, INTENT(OUT) :: DSBAR
              REAL(KIND=8) ,OPTIONAL, INTENT(OUT) :: THETA
            END SUBROUTINE INVAR
          END INTERFACE 
        END MODULE INVAR__genmod
