        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:16 2019
        MODULE LOAD_FUNCTION__genmod
          INTERFACE 
            SUBROUTINE LOAD_FUNCTION(LF,DTIM,AL)
              REAL(KIND=8), INTENT(IN) :: LF(:,:)
              REAL(KIND=8), INTENT(IN) :: DTIM
              REAL(KIND=8), INTENT(INOUT) :: AL(:)
            END SUBROUTINE LOAD_FUNCTION
          END INTERFACE 
        END MODULE LOAD_FUNCTION__genmod
