        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:14 2019
        MODULE MESH_SIZE__genmod
          INTERFACE 
            SUBROUTINE MESH_SIZE(ELEMENT,NOD,NELS,NN,NXE,NYE,NZE)
              CHARACTER(LEN=15), INTENT(IN) :: ELEMENT
              INTEGER(KIND=4), INTENT(IN) :: NOD
              INTEGER(KIND=4), INTENT(OUT) :: NELS
              INTEGER(KIND=4), INTENT(OUT) :: NN
              INTEGER(KIND=4), INTENT(IN) :: NXE
              INTEGER(KIND=4), INTENT(IN) :: NYE
              INTEGER(KIND=4) ,OPTIONAL, INTENT(IN) :: NZE
            END SUBROUTINE MESH_SIZE
          END INTERFACE 
        END MODULE MESH_SIZE__genmod
