        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 12:05:21 2019
        MODULE SPARIN__genmod
          INTERFACE 
            SUBROUTINE SPARIN(KV,KDIAG)
              REAL(KIND=8), INTENT(INOUT) :: KV(:)
              INTEGER(KIND=4), INTENT(IN) :: KDIAG(:)
            END SUBROUTINE SPARIN
          END INTERFACE 
        END MODULE SPARIN__genmod
