        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 12:05:24 2019
        MODULE SPARIN_GAUSS__genmod
          INTERFACE 
            SUBROUTINE SPARIN_GAUSS(KV,KDIAG)
              REAL(KIND=8), INTENT(OUT) :: KV(:)
              INTEGER(KIND=4), INTENT(IN) :: KDIAG(:)
            END SUBROUTINE SPARIN_GAUSS
          END INTERFACE 
        END MODULE SPARIN_GAUSS__genmod
