        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 02 21:50:19 2019
        MODULE VMFLOW__genmod
          INTERFACE 
            SUBROUTINE VMFLOW(STRESS,DSBAR,VMFL)
              REAL(KIND=8), INTENT(IN) :: STRESS(:)
              REAL(KIND=8), INTENT(IN) :: DSBAR
              REAL(KIND=8), INTENT(OUT) :: VMFL(:)
            END SUBROUTINE VMFLOW
          END INTERFACE 
        END MODULE VMFLOW__genmod
